### ISSUE TITLE
假的，随便拷贝的单片机的代码，大家可以散了

### ISSUE THREAD

**Issue by vitanie** [Awesome-HarmonyOS/HarmonyOS#10]
不知作者这么明目张胆蹭热点的目的是什么

**Comment by zd938780519** [comment]
刚看就感觉不太对，这代码也太随意了！





------------------ 原始邮件 ------------------
发件人: "vitanie"<notifications@github.com>;
发送时间: 2019年8月10日(星期六) 中午11:04
收件人: "Awesome-HarmonyOS/HarmonyOS"<HarmonyOS@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Awesome-HarmonyOS/HarmonyOS] 假的，随便拷贝的单片机的代码，大家可以散了 (#10)




不知作者这么明目张胆蹭热点的目的是什么

**Comment by ysy950803** [comment]
这不会是哪个脑门一热的大学生搞的吧？年轻人有热血可以，但不能造假呀。

**Comment by langyo** [comment]
main 那里写个 while(1) 哄谁呢
