### ISSUE TITLE
HuaweiLiteOSKernelDevGuide.chm无法打开里面的内容

### ISSUE THREAD

**Issue by WilliamYinwei** [Awesome-HarmonyOS/HarmonyOS#12]
HuaweiLiteOSKernelDevGuide.chm无法打开里面的内容

_Originally posted by @WilliamYinwei in https://github.com/Awesome-HarmonyOS/HarmonyOS/issues/9#issuecomment-520122109_

**Comment by Awesome-HarmonyOS** [comment]
Windows下打开。

**Comment by WilliamYinwei** [comment]
是在Windows 10下打开的

**Comment by WilliamYinwei** [comment]
已OK

**Comment by sosyz** [comment]
假的研究啥呀
