### ISSUE TITLE
鸿蒙原型下载，需付费0.1元

### ISSUE THREAD

**Issue by fallleaf** [Awesome-HarmonyOS/HarmonyOS#32]
https://yuedu.baidu.com/ebook/95d1c1a6daef5ef7ba0d3c52?fr=aladdin&key=%E5%B1%B1%E6%B5%B7%E7%BB%8F

搜索“鸿蒙”，立秒可见

**Comment by JunjieYuan** [comment]
这个链接是《山海经》。
