### ISSUE TITLE
所以真的就是几年前的liteos换了一个名字？被阿里os踩的那个？

### ISSUE THREAD

**Issue by livefa** [Awesome-HarmonyOS/HarmonyOS#35]
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by JunhuaiYang** [comment]
一个骗star的账号搞的那么认真干嘛

**Comment by Awesome-HarmonyOS** [comment]
The underlying layer of HarmonyOS is composed of HarmonyOS micro kernel, Linux kernel and Lite OS and it will become a complete hongmeng micro kernel architecture in the future.
