### ISSUE TITLE
HarmonyOS, HormonyOS or HoemonyOS

### ISSUE THREAD

**Issue by csukuangfj** [Awesome-HarmonyOS/HarmonyOS#40]
README.md 有各种名字， 到底是哪一个?

**Comment by csukuangfj** [comment]
是假的。

源自
https://github.com/Awesome-HarmonyOS/HarmonyOS/tree/master/Huawei_LiteOS

@Awesome-HarmonyOS 就是蹭热点而已.

**Comment by Awesome-HarmonyOS** [comment]
已修正。

**Comment by csukuangfj** [comment]
@Awesome-HarmonyOS 
没改完！
