### ISSUE TITLE
真是无聊，骗子，蹭热点

### ISSUE THREAD

**Issue by hooliy** [Awesome-HarmonyOS/HarmonyOS#43]
代码全是 https://github.com/LiteOS/LiteOS 这个库的代码

**Comment by kang558** [comment]
作者是蹭热度忽悠别人来的

**Comment by Awesome-HarmonyOS** [comment]
我已经写得很清楚了。A curated list of awesome things related to HarmonyOS. github “awesome”系统列请了解一下。
