### ISSUE TITLE
看到有人喷我就放心了，为了蹭热度脸都不要。

### ISSUE THREAD

**Issue by evolify** [Awesome-HarmonyOS/HarmonyOS#47]

**Comment by Awesome-HarmonyOS** [comment]
我已经写得很清楚了。A curated list of awesome things related to HarmonyOS. github “awesome”系统列请了解一下。

**Comment by evolify** [comment]
既然提到了awesome系列，那么请你摸着自己的良心说一下，你这个真的能算的上‘awesome’？项目名字确定不是故意的？Code中的Huawei_LiteOS 又是几个意思？
