### ISSUE TITLE
热度狗，要真是华为开源也肯定是在华为官网里 Hot dog, if it is really Huawei open source, it must be in Huawei's official website.

### ISSUE THREAD

**Issue by Fish741** [Awesome-HarmonyOS/HarmonyOS#51]
热度狗，要真是华为开源也肯定是在华为官网里
Hot dog, if it is really Huawei open source, it must be in Huawei's official website.

**Comment by Awesome-HarmonyOS** [comment]
我已经写得很清楚了。A curated list of awesome things related to HarmonyOS. github “awesome”系统列请了解一下。
