### ISSUE TITLE
这个是假的，我问了华为客服了

### ISSUE THREAD

**Issue by mzxhtml** [Awesome-HarmonyOS/HarmonyOS#52]
![20190812112434](https://user-images.githubusercontent.com/32251251/62844443-05fcb380-bcf4-11e9-86df-f033e0d1cc50.png)

**Comment by Awesome-HarmonyOS** [comment]
我已经写得很清楚了。A curated list of awesome things related to HarmonyOS. github “awesome”系统列请了解一下。
