### ISSUE TITLE
关于report这个repository的论点

### ISSUE THREAD

**Issue by ricardoCyy** [Awesome-HarmonyOS/HarmonyOS#60]
1. Awesome-HarmonyOS关闭了我的issue [Guys, complaint is cheap, report him.](https://github.com/Awesome-HarmonyOS/HarmonyOS/issues/55), 并给出理由

> 我已经写得很清楚了。A curated list of awesome things related to HarmonyOS. github “awesome”系统列请了解一下。

2. 应他的要求我了解了一下，在github中搜索"awesome"关键词，在返回我的**前五页搜索结果中**，**所有**的"awesome"系列项目都在repository-name中写有**awesome-{XXX}**(XXX=project_name)，并且只有一位user可能觉得太"awesome"了，使用了"awesome-{XXX}"作为自己的用户名。

3. 综上，在我了解"awesome"系列之后，我认为这个repository的主要问题（或者说为什么大家会觉得 **”被骗了“** ）（至少）是： **不规范的命名awesome-list**，使大家误以为这是官方发布的源码。

4. 至于产生这种误导的原因，我个人更愿意相信应该是”Awesome-HarmonyOS“觉得HarmonyOS太"awesome"了吧 ：)

5. 我已经report了"Awesome-HarmonyOS"，理由是"**MISLEADING** people into thinking this repository as an official release of Huawei's newly released "HarmonyOS""。

以上是我的个人观点，如果有问题希望大家能好心指正，我愿意修改/撤回我的report，如果这个论点是错误的。

**Comment by Awesome-HarmonyOS** [comment]
了解了你的观点，我会加上说明。

**Comment by weinierfei** [comment]
这人刚开始的时候将华为的logo作为自己的头像,现在换掉了;然后还删除了我的两个issues
